version: '2'
services:
  db:
    image: mariadb:latest
    environment:
     - MYSQL_ROOT_PASSWORD=Eak829ij23
     - MYSQL_USER=dba
     - MYSQL_PASSWORD=zoilo367
     - TERM=xterm-256color
    ports:
      - "3306:3306"
    volumes:
       - db-volume:/var/lib/mysql
  redis:
    image: redis
  apache:
    build: ./apache-php
    ports:
        - "80:80"
        - "443:443"
        - "9000:9000"
    links:
      - db
      - redis
    volumes:
        - ./html:/var/www/html
        - ./apache-php/php.ini:/etc/php/conf.d/30-custom.ini:ro
        - ./apache-php/apache.conf:/etc/apache2/sites-enabled/apache.conf:ro
    environment:
        - TERM=xterm-256color
        - DB_CONNECTION=mysql
        - DB_HOST=db
        - DB_PORT=3306
        - DB_DATABASE=monitor
        - DB_USERNAME=dba
        - DB_PASSWORD=zoilo367
        - REDIS_HOST=redis
        - REDIS_PASSWORD=null
        - REDIS_PORT=6379



volumes:
  db-volume:
